apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: db
    spec:
      containers:
      - image: mysql
        name: mysql
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: abc
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: dbvol

      volumes:
        - name: dbvol
          persistentVolumeClaim:
            claimName: mysql-pvc
status: {}
