apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Leave empty to match manual provisioning
  awsElasticBlockStore:
    volumeID: vol-0543773fa75cd5d49  # Make sure this matches the volume created manually
    fsType: ext4

