apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: custom-storage
  hostPath:
    path: /mnt/disk   # Change this to the path you mounted on the worker node
  volumeMode: Filesystem

