apiVersion: apps/v1
kind: Deployment
metadata:
  name: register-pod
  labels:
    app: register
spec:
  replicas: 2
  selector:
    matchLabels:
      app: register
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
        - name: register-container
          image:  akhilmylaram/register:latest
          ports: 
            - name: register-port
              containerPort: 80
              
