apiVersion: v1
kind: Service
metadata:
  name: register-service
spec:
  ports:
    - port: 8090
      targetPort: 80
      protocol: TCP
      nodePort: 30002
  selector:
    app: register
  type: NodePort
